title = "EZPC.fi"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Sivut"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Tietoja"
    url = "/about"
    weight = 20
